# Generated by Django 4.2.4 on 2023-08-22 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin2_app', '0002_alter_author_birthday_alter_kicks_kick_time_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kicks',
            name='kick_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 20, 35, 31, 433517)),
        ),
    ]
