# Generated by Django 4.2.4 on 2023-08-22 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin2_app', '0003_alter_kicks_kick_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kicks',
            name='kick_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 20, 44, 11, 982867)),
        ),
    ]
