# Generated by Django 4.2.4 on 2023-08-24 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin2_app', '0004_alter_kicks_kick_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kicks',
            name='kick_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 19, 6, 0, 907052)),
        ),
    ]
