# Generated by Django 4.2.4 on 2023-08-27 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin2_app', '0005_alter_kicks_kick_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kicks',
            name='kick_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 18, 5, 4, 727733)),
        ),
    ]
